#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
----------------------------------------------------------
   _  __________  ____  ______  _____ ____  _____  ___  __
  | |/ /_  __/ / / / / / / __ \/ ___// __ \/   \ \/ / |/ /
  |   / / / / /_/ / / / / /_/ /\__ \/ / / / /| |\  /|   /
 /   | / / / __  / /_/ / _, _/___/ / /_/ / ___ |/ //   |
/_/|_|/_/ /_/ /_/\____/_/ |_|/____/_____/_/  |_/_//_/|_|

Brought to you by xthursdayx
----------------------------------------------------------
GID/UID
----------------------------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

time32="$(date +%Y)"

if [[ "${time32}" == "1970" || "${time32}" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
    echo '
╔═════════════════════════════════════════════════════════════════════════════╗
║                                                                             ║
║        Your Docker Host is running an outdated version of libseccomp        ║
║                                                                             ║
║    To fix this, please visit https://docs.linuxserver.io/faq#libseccomp     ║
║                                                                             ║
║                 Apps will not behave correctly without this                 ║
║                                                                             ║
╚═════════════════════════════════════════════════════════════════════════════╝
'
    sleep infinity
fi

lsiown abc:abc /app
lsiown abc:abc /config
lsiown abc:abc /defaults

