#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/comics \
	/comics/.yacreaderlibrary \
	/config/.local/share/YACReader/YACReaderLibrary

# set YACReaderLibrary.ini
if [ ! -f /config/.local/share/YACReader/YACReaderLibrary/YACReaderLibrary.ini ]; then
  cp /defaults/YACReaderLibrary.ini /config/.local/share/YACReader/YACReaderLibrary/YACReaderLibrary.ini
fi

# permissions
find /config -not \( -user abc -and -group abc \) -exec chown abc:abc {} +
find /defaults -not \( -user abc -and -group abc \) -exec chown abc:abc {} +
find /app -not \( -user abc -and -group abc \) -exec chown abc:abc {} +
find /comics -not \( -user abc -and -group abc \) -exec chown abc:abc {} +
