#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
----------------------------------------------------------
            _                    _                   
       _   | |                  | |                  
 _   _| |_ | | _  _   _  ____ _ | | ____ _   _ _   _ 
( \ / )  _)| || \| | | |/ ___) || |/ _  | | | ( \ / )
 ) X (| |__| | | | |_| | |  ( (_| ( ( | | |_| |) X ( 
(_/ \_)\___)_| |_|\____|_|   \____|\_||_|\__  (_/ \_)
                                        (____/       
                                        
Brought to you by xthursdayx
----------------------------------------------------------
GID/UID
----------------------------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
