#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
----------------------------------------------------------
       _   _                        _                  
 __  _| |_| |__  _   _ _ __ ___  __| | __ _ _   ___  __
 \ \/ / __| '_ \| | | | '__/ __|/ _` |/ _` | | | \ \/ /
  >  <| |_| | | | |_| | |  \__ \ (_| | (_| | |_| |>  < 
 /_/\_\\__|_| |_|\__,_|_|  |___/\__,_|\__,_|\__, /_/\_\
                                            |___/      
Brought to you by xthursdayx
----------------------------------------------------------
GID/UID
----------------------------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
