#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/comics \
	/comics/.yacreaderlibrary \
	/config/.local/share/YACReader/YACReaderLibrary

# set webserver port on first install
if [ ! -f /config/.local/share/YACReader/YACReaderLibrary/YACReaderLibrary.ini ]; then
  cp /defaults/YACReaderLibrary/ini /config/.local/share/YACReader/YACReaderLibrary/YACReaderLibrary.ini
fi

# permissions
chown -R abc:abc \
		/config \
		/defaults \
		/YACReaderLibraryServer \
		/comics	
